#include "render_common.h"

u32 mdGetVertexAttributeTypeCount(enum MdVertexBufferAttributeType type)
{
	switch (type)
	{
	case MD_VERTEX_BUFFER_ATTRIBUTE_TYPE_FLOAT:
	case MD_VERTEX_BUFFER_ATTRIBUTE_TYPE_UNSIGNED_INT:
		return 1;
	case MD_VERTEX_BUFFER_ATTRIBUTE_TYPE_FLOAT2:
	case MD_VERTEX_BUFFER_ATTRIBUTE_TYPE_UNSIGNED_INT2:
		return 2;
	case MD_VERTEX_BUFFER_ATTRIBUTE_TYPE_FLOAT3:
	case MD_VERTEX_BUFFER_ATTRIBUTE_TYPE_UNSIGNED_INT3:
		return 3;
	case MD_VERTEX_BUFFER_ATTRIBUTE_TYPE_FLOAT4:
	case MD_VERTEX_BUFFER_ATTRIBUTE_TYPE_UNSIGNED_INT4:
		return 4;
	default:
		MD_UNTOUCHABLE();
		return 0;
	}
}

u32 mdGetVertexAttributeTypeSize(enum MdVertexBufferAttributeType type)
{
	switch (type)
	{
	case MD_VERTEX_BUFFER_ATTRIBUTE_TYPE_FLOAT:
	case MD_VERTEX_BUFFER_ATTRIBUTE_TYPE_FLOAT2:
	case MD_VERTEX_BUFFER_ATTRIBUTE_TYPE_FLOAT3:
	case MD_VERTEX_BUFFER_ATTRIBUTE_TYPE_FLOAT4:
		return sizeof(float) * mdGetVertexAttributeTypeCount(type);
	case MD_VERTEX_BUFFER_ATTRIBUTE_TYPE_UNSIGNED_INT:
	case MD_VERTEX_BUFFER_ATTRIBUTE_TYPE_UNSIGNED_INT2:
	case MD_VERTEX_BUFFER_ATTRIBUTE_TYPE_UNSIGNED_INT3:
	case MD_VERTEX_BUFFER_ATTRIBUTE_TYPE_UNSIGNED_INT4:
		return sizeof(u32) * mdGetVertexAttributeTypeCount(type);
	default:
		MD_UNTOUCHABLE();
		return 0;
	}
}